### PR TITLE
config: Fix support for multiple levels of same layer

### LINKED ISSUE #294: Fix support for multiple levels of same layer

### PR DESCRIPTION
**Pull request by tadatuta**
Closes #294

Note: actually multiple levels of same layer is kinda antipattern which will be harmful in the future (see https://github.com/bem/bem-sdk/pull/295#discussion_r176905828).

But right now we decided to keep it to use with libs without own `.bemrc`. In other cases should be possible to merge semantically identical layers into one folder.

### CODE REVIEW

File: packages/config/index.js [hunk 1]
```diff
@@ -201,28 +201,32 @@ BemConfig.prototype.levels = function(setName) {
...
+                    var levelPath = lvl.path || (lvl.layer + '.blocks'); // TODO: Use `@bem/sdk.file.naming`
 
-            return _this.levelMap().then(levelsMap => levelsMap[levelPath]);
-        })).then(flatten);
+                    acc.push(levelsMap[levelPath]);
+
+                    return acc;
+                }, []);
+            }));
+        }).then(flatten);
```
Comment (qfox) [inline packages/config/index.js:229]: Let's play!

File: packages/config/test/async.test.js [hunk 2]
```diff
@@ -490,4 +490,37 @@ describe('async', () => {
 
         return expect(actual).to.eventually.deep.equal(expected);
     });
+
+    it('should return levels set with custom paths', () => {
+        const bemConfig = config([{
+            levels: [
+                { layer: 'common', path: 'node_modules/lib/common.blocks' },
+                { layer: 'common', path: 'common.blocks' },
```
Comment (qfox) [inline packages/config/test/async.test.js:498]: How to get the good `path` value for `{ block: 'button', layer: 'common', tech: 'css' }` cell if we have 2 paths for a `common` layer?

**Review by qfox — CHANGES_REQUESTED** [review]

File: packages/config/test/async.test.js (hunk 2 above)
Comment (tadatuta) [reply packages/config/test/async.test.js:498]: dunno, let's talk about it

Comment (qfox) [reply packages/config/test/async.test.js:498]: Decided to merge it in as is.
